#!/usr/bin/env python

import re

size = raw_input('\nPlease enter the text file size: ')

if size.strip() in ['65','66','67']:
    print "\nCorrect! The fourth character is '%s'.\n"%chr(69)
    print """Did you know:    
    The solution is something of which about three million exist.
    """
else:
    print "\nSorry, please try again.\n"
    if not re.search('\A\d+\Z',size):
        print "Try to enter the size as a single number, e.g. '123'"

